export const getProductsData = (language) => {
  const isHi = language === "hi";

  return [
    {
      id: 'interlocking-grey',
      name: isHi ? 'ग्रे इंटरलॉकिंग पेवर' : 'Grey Interlocking Paver',
      desc: isHi ? 'उच्च गुणवत्ता का कंक्रीट पेवर, भारी भार के लिए उपयुक्त।' : 'High-quality concrete paver, suitable for heavy loads.',
      priceMin: 40,
      priceMax: 60,
      priceUnit: 'sqft',
      image: '/images/interlocking-street-image-grey.jpg',
      tag: isHi ? 'बेस्टसेलर' : 'Bestseller',
      tagColor: 'bg-primary/10 text-primary',
    },
    {
      id: 'interlocking-red',
      name: isHi ? 'रेड इंटरलॉकिंग पेवर' : 'Red Interlocking Paver',
      desc: isHi ? 'रंगीन और टिकाऊ पेवर, लैंडस्केपिंग के लिए परफेक्ट।' : 'Colorful and durable paver, perfect for landscaping.',
      priceMin: 45,
      priceMax: 65,
      priceUnit: 'sqft',
      image: '/images/interlocking-street-image-red.jpg',
      tag: isHi ? 'नया' : 'New',
      tagColor: 'bg-secondary/10 text-secondary',
    },
    {
      id: 'interlocking-yellow',
      name: isHi ? 'येलो इंटरलॉकिंग पेवर' : 'Yellow Interlocking Paver',
      desc: isHi ? 'चमकीला और टिकाऊ, पार्किंग और पार्कों के लिए।' : 'Bright and durable, for parking lots and parks.',
      priceMin: 42,
      priceMax: 62,
      priceUnit: 'sqft',
      image: '/images/interlocking-street-image-yellow.jpg',
      tag: isHi ? 'उपलब्ध' : 'Available',
      tagColor: 'bg-tertiary/10 text-tertiary',
    },
    {
      id: 'petrol-pump-grey',
      name: isHi ? 'पेट्रोल पंप ग्रे पेवर' : 'Petrol Pump Grey Paver',
      desc: isHi ? 'अत्यधिक भार के लिए डिज़ाइन किया गया।' : 'Designed for extremely heavy loads.',
      priceMin: 70,
      priceMax: 90,
      priceUnit: 'sqft',
      image: '/images/swastika-interlocking-pertol-bricks-grey.jpg',
      tag: isHi ? 'हेवी ड्यूटी' : 'Heavy Duty',
      tagColor: 'bg-primary/10 text-primary',
    },
    {
      id: 'petrol-pump-red',
      name: isHi ? 'पेट्रोल पंप रेड पेवर' : 'Petrol Pump Red Paver',
      desc: isHi ? 'पेट्रोल पंप के लिए विशेष रंग पेवर।' : 'Special colored paver for petrol pumps.',
      priceMin: 72,
      priceMax: 92,
      priceUnit: 'sqft',
      image: '/images/swastika-interlocking-pertol-bricks-red.jpg',
      tag: isHi ? 'उपलब्ध' : 'Available',
      tagColor: 'bg-secondary/10 text-secondary',
    },
    {
      id: 'petrol-pump-yellow',
      name: isHi ? 'पेट्रोल पंप येलो पेवर' : 'Petrol Pump Yellow Paver',
      desc: isHi ? 'चमकीला और दृश्यमान, पेट्रोल पंप के लिए।' : 'Bright and visible, for petrol pumps.',
      priceMin: 70,
      priceMax: 90,
      priceUnit: 'sqft',
      image: '/images/swastika-interlocking-pertol-bricks-yellow.jpg',
      tag: isHi ? 'उपलब्ध' : 'Available',
      tagColor: 'bg-tertiary/10 text-tertiary',
    },
    {
      id: 'cement',
      name: isHi ? 'सीमेंट' : 'Cement',
      desc: isHi ? 'प्रीमियम ग्रेड सीमेंट, सभी निर्माण कार्यों के लिए।' : 'Premium grade cement for all construction works.',
      priceMin: 380,
      priceMax: 420,
      priceUnit: 'bag',
      image: '/images/acc-opc-cement.webp',
      tag: isHi ? 'बेस्टसेलर' : 'Bestseller',
      tagColor: 'bg-primary/10 text-primary',
    },
    {
      id: 'red-sand',
      name: isHi ? 'लाल बालू' : 'Red Sand',
      desc: isHi ? 'उच्च गुणवत्ता की रेत, निर्माण के लिए।' : 'High-quality sand for construction.',
      priceMin: 40,
      priceMax: 60,
      priceUnit: 'sqft',
      image: '/images/red-sand.jpg',
      tag: isHi ? 'उपलब्ध' : 'Available',
      tagColor: 'bg-secondary/10 text-secondary',
    },
    {
      id: 'white-sand',
      name: isHi ? 'सफेद बालू' : 'White Sand',
      desc: isHi ? 'सफेद रेत, विशेष लैंडस्केपिंग के लिए।' : 'White sand for special landscaping.',
      priceMin: 60,
      priceMax: 80,
      priceUnit: 'sqft',
      image: '/images/white-sand.jpg',
      tag: isHi ? 'उपलब्ध' : 'Available',
      tagColor: 'bg-tertiary/10 text-tertiary',
    },
    {
      id: 'small-stone',
      name: isHi ? 'छोटे पत्थर' : 'Small Stones',
      desc: isHi ? '10-20mm के गिट्टी, कंक्रीट के लिए।' : '10-20mm aggregates for concrete.',
      priceMin: 35,
      priceMax: 50,
      priceUnit: 'sqft',
      image: '/images/small-stone-gitti.jpg',
      tag: isHi ? 'उपलब्ध' : 'Available',
      tagColor: 'bg-primary/10 text-primary',
    },
    {
      id: 'large-stone',
      name: isHi ? 'बड़े पत्थर' : 'Large Stones',
      desc: isHi ? '20-40mm के गिट्टी, फाउंडेशन के लिए।' : '20-40mm aggregates for foundation.',
      priceMin: 40,
      priceMax: 55,
      priceUnit: 'sqft',
      image: '/images/large-stone-gitti.jpg',
      tag: isHi ? 'उपलब्ध' : 'Available',
      tagColor: 'bg-secondary/10 text-secondary',
    },
    {
      id: 'pipes',
      name: isHi ? 'पाइप्स' : 'Pipes',
      desc: isHi ? 'विभिन्न आकारों की कंक्रीट पाइप्स।' : 'Concrete pipes in various sizes.',
      priceMin: 200,
      priceMax: 1500,
      priceUnit: 'meter',
      image: '/images/pipe-largersize.jpg',
      tag: isHi ? 'उपलब्ध' : 'Available',
      tagColor: 'bg-tertiary/10 text-tertiary',
    }
  ];
};
